version: 2.1
jobs:
    build:
      docker:
        - image: mcr.microsoft.com/playwright:v1.29.0-focal
      working_directory: ~/app
      steps:
        - checkout
        - run: npm i
        - run: npx playwright install chrome
        - run:
            command: npx playwright test --config=./playwright.config.js

workflows:
    main-wofkflow:
      jobs:
        - build
