version: 2.1
jobs:
    build:
      docker:
        - image: mcr.microsoft.com/playwright:v1.34.2-focal
      working_directory: ~/app
      steps:
        - checkout
        - run: npm i
        - run: npx playwright install chrome
        - run:
            command: circleci tests glob "tests/**/*.js" | circleci tests run --command="PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml xargs npx playwright test --config=./playwright.config.js --reporter=junit,line" --verbose
        - store_test_results:
            path: results.xml

workflows:
    main-wofkflow:
      jobs:
        - build
